### ISSUE TITLE
Roadmap (Aug. 2019)

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#1725]
# Features

- [ ] Using child process to run child process.
- [ ] New plugin option api - `restrart` - used for re-launch dev process.
- [ ] New plugin option api - `modifyHTML` - used for modify html before it's sent to browser or generated.
- [ ] Depth of extracted headers. (Issue: #984, #1715, MR: #1111)

# Discussion

To ensure the purity of roadmap, we closes comments for this issue. If you want to participate in the discussion, please create a corresponding issue to continue.

**Comment by f3ltron** [comment]
I saved the features asked. We will communicate as soon as possible about the roadmap !
